name: spell_hf
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - transformers==4.48
      - accelerate
      - datasets
      - huggingface-hub
      - matplotlib
      - mlflow
      - numpy
      - pandas
      - pillow
      - scikit-learn
      - scipy
      - tokenizers
      - peft

